language: node_js
node_js:
  - '8'
env:
  global:
    # doubleface GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-cesu
    - secure: "zoE7aObfPgJ9+JzWeRM4GbYGGiTfBER2dvj3FALqJRrReAc2V1GUKZcW5hZDm4CaWN+tZ0sS97CxfR7SXoNPRlZFVEnlF74XDaC1WNT6H06z3Wp2/zapdbUW7BETHNZd3OmFqcOynW3gdQ3/P7KdlkNLF0FwLI0fpFaF5X+AAWGIgFesQXve/10xGuXhPjMWpcahVPM3P2GN4tlFaJBjmTscB00d5+yUYbI4/qHMk2YQWNCqBWNXWfxVLQx/WoYJlXBWpNmDzDCCboLll0xjSHkAGLvzwI/RLcnrPrjfNzlY+QOTDgemicAbcW9Nx2vVS6vYvj3Gzv8rDhGSu2B7ecGWvWpaDurcyyJL+fAbPM046qXUJnSTQwHooZhfa/5ffzCY7ZD/fXfo5Pc37HrD8bINNx0gkZTn4t2G3ZpWGE3UGReT7Dozck8sdS+mbwYADYdHpNuBBbw2TQ+ChHvV96krO02NauKq+PrPB7Pnt/tQKH3kCY8rQsRKakhL2vge6qw1csOzdCj+nTT7qcJL+E6L3vh3UhbGTepHUK1Fry4+vNi3o2pX//zHeKMgmz7bry3YWpKX+E+padJwYKHAd+G6fnxWzox+NERZoUCRg3vbTx1A4qI/KFcEKMf7pYsZShflrZAuEqUiVZqhfJjT1AMOCRZjLSo24xwZrW27gO4="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-cesu
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-cesu
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy
    on:
      branch: prod
