language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-cesu.git"
  - secure: kon2s32GM9NRKpQm0JqFW7ychTnLB0uZJzxVvW8hUNsSqJJTiHnrVx8qxlmoACJkSMBt8NoySoJnso5/3irtQLqDpPr1ylchlhVi3K8N/i9HNsBr0VUr3GeU8VLv4F7HSgAC+SBJiUIcp9ZaBbdn1+D5/4aHmjjfmJSemZOil/CVXxLCmxRVQjMXz7hGn/K8+ntgG9WYHzwZOtcwm2fWk0MHst9C9lsgM1rXCWSWJ9McFNxpdL7HdSbVP4i9by7WZwV+Ti9LhBODoDOE95UfatZUBG2G1zt73Y/lliEGy9EE4fVilAMkT6rRlL5scYcxDZqqPCAFIeujJorxicY0SR5ygtBh9k46LuDoJqSDz5PyQ5EfOxq60oJ6aAScFR9a/PTXZdpwPJ59O/MKQPmMG3vDdAxK+0c570R4CThvgybtFl0TF5H69WcC+w4SVl8hZqYN1pvVC+fEHlgTWiZ60pVNrXdend+yBsa5/VqhlJuPMCVaMFBHxgEgFlbwXw9kz5FDsVmqOk7UPPfHn/R4WOLWN1OAOsG9f59+J9jeAofHVDedwJlhLW9q6osVhFy+DvrNjoQSBjJH0SE080K1sWxg4T5cQV2+rrL1j64MzdJXb5rVryVMCxsxp8HGObA/xcrfs15JK9L+xHdhmp1vD9SeeqMvFJTy9WCIwN0DbIo=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
# - yarn run check
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_9cf751988ff9_key -iv $encrypted_9cf751988ff9_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
