language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-cesu
    - secure: "UYPApSGWzhtQi9HI+rl32gXYu78C5Ptt25eGZAUXh7LBTCXT43VKDFC0beOq0+4OaEDB0hoA4DdWXSrkAEQfs7XgshbEu/zqoKI0Dcgsnsv1lf0rMCSvSv5AfMaabYJbJ0A1/wjojSJ3eVxWM28SfHZpG6c0CUAiFQD27v6tADT0B5aZd7mzdMKVUcHXq4XMVnbGTOuqMrzEZPRsQ3LPZdLQo/+JyT9Q2QTf/qZVzWvLsX8SxnDudMyPwPoOwt8u89YNFnbDpWQSHhUtohYKIuUo1CBI0cQ6AbjIjNe74qhAFh6IQCSInJGQ3GLrRkkTV8jAc7LmMhufwxamhJ4OTozeO1rpFEYRfmZ8INlxnADP3Jid23tek5+7Jl1D4xpYDqkGCLINp4sDRpFf9II8+QZBFoVflsxKFClsfsLBt8hHwOyo7VJTSCfAT/AMMSpTx3yysLOazfrEEDmkaUHa1uypn9K3IWIP4bzmtjRPbGQ/gNs0EYEKOyJa848LWMrJaAyAH/nf+ynITgno3ES6l0EYrRqIL8IJS7v2aq38XDSEytB6UsqJslYLxokqcOJRhEhhMEKLt76DEnjoDGqh7GXoPMDN+uji6IHglMHvMocbp4xSxkHMkptIAS5lA5b9mniefmUUgbHZ/SBNaK8+2IAAOQc41llzWXjMGcafkDw="
    # Cozy REGISTRY_TOKEN
    - secure: "wN4OKvESb6YZagAeMorGxmwfHyW7Iqf80U3MXmtUthlmOfZM2genzzAYKK+eU/fVV58UqyttbxpEggrMppvqbxx0DtTgxMLXiSV/GvqnKEvyMlAwpc+ypP9nX7mzPoxny9hODEsy0VxbH843OvmrLj0rl1Ws6JjA1CwV+QZc9gIBMq/pW8P+vg/588yjPq2UpXwCDeNqQY7wexffFDfSd/I86aUg5zJCbvnvGwzPE7a+guI+jcB6+swsDFyeiZTeXAqdL3Z4PZHNjTHO6GTXCNKC8L619vdoDL/lqsEEOtPT4PbJq5i3M8P66mwkp7brlwPr+guNUsiEhW7PaqxbNssDpX1ESyit0j5iDC4+udiYGkJ85q6n7rX4PH6Vn3ORGV3F1yW2Drh6LlAH/6xeWdKh3WsaZaBqOZk3LKSQRcJZYfGxxL+foRV/sxR6+7+y8+CqtoKk6nHFGPjfozUbdEZ0GyRNK8n4vuO3A5ESUHGzmFNi26N4K+eRZJpaLYhek0/AO5SDrbE9NipURb+OiQyumDTqERdVH21VhbVdMAkD4KUAQ9+uVh6Cs0rhPIFi7xH8TZDAW2n7otgbGD/noemmqowEozTV43Sg8Ex6dPiAGY8OUVFOJx1dFTMJbQYQGgmq7WRV6fUF5dMx0f0wtjRWn3Pc8yQmzRhjpxf7Ax8="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-cesu
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-cesu
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest && yarn deploy && yarn cozyPublish
    on:
      branch: prod
